export { default as getDishes } from './graphql/getDishes';
export { default as postComment } from './graphql/postComment';
export { default as getComments } from './graphql/getComments';
export { default as getSpecials } from './graphql/getSpecials';
export { default as getPosts } from './graphql/getPosts';
export { default as getRecentPosts } from './graphql/getRecentPosts';
export { default as getPostDetails } from './graphql/getPostDetails';
export { default as getGalleryImages } from './graphql/getGalleryImages';
export { default as getLatestImages } from './graphql/getLatestImages';